export const BASE_ARTICLES = [
  {
    image: "/images/insights/article-1.jpg",
    category: "Tech & Innovations",
    title: "A Review of Nigeria's National Blockchain Policy",
    excerpt: "Nigeria has displayed a growing interest in blockchain technology and cryptocurrencies, recognising their potential benefits in areas such as financial inclusion, transparency, and corruption reduction.",
    author: "EBERE OJADUA",
    publishedAt: "5th May 2026",
    readTime: "5 mins read",
    slug: "nigeria-blockchain-policy",
  },
  {
    image: "/images/insights/article-2.jpg",
    category: "Policy Analysis",
    title: "Boosting Trade Development Across West Africa",
    excerpt: "Trade blocs play a pivotal role in promoting economic integration and cooperation among countries, fostering regional growth and prosperity.",
    author: "DEJI MACAULAY",
    publishedAt: "5th May 2026",
    readTime: "5 mins read",
    slug: "boosting-trade-west-africa",
  },
  {
    image: "/images/insights/article-3.jpg",
    category: "Tech & Innovation",
    title: "A Review of the Data Protection Act 2020: Strengths and Weaknesses",
    excerpt: "Executive Summary This Policy Brief reviews the Data Protection Act 2020 (the Act), which protects individual privacy rights across digital platforms.",
    author: "CHINWE OHANELE",
    publishedAt: "5th May 2026",
    readTime: "5 mins read",
    slug: "data-protection-act-2020",
  },
  {
    image: "/images/insights/article-4.jpg",
    category: "Policy Analysis",
    title: "How Big Data Enables and Constrains AI Development in Africa",
    excerpt: "The report discusses the opportunities and challenges of using big data and AI for sustainable development in Africa and offers recommendations for policymakers, businesses, and researchers.",
    author: "CHINWE OHANELE",
    publishedAt: "5th May 2026",
    readTime: "5 mins read",
    slug: "big-data-ai-africa",
  },
  {
    image: "/images/insights/article-1.jpg",
    category: "Tech & Innovation",
    title: "Digital Infrastructure and the Future of African Governance",
    excerpt: "Examining how digital infrastructure investment is reshaping the relationship between governments and citizens across Africa.",
    author: "EBERE OJADUA",
    publishedAt: "12th April 2026",
    readTime: "6 mins read",
    slug: "digital-infrastructure-african-governance",
  },
  {
    image: "/images/insights/article-2.jpg",
    category: "Policy Analysis",
    title: "The AfCFTA and the Road to Continental Free Trade",
    excerpt: "An assessment of implementation progress under the African Continental Free Trade Area two years after its formal entry into force.",
    author: "DEJI MACAULAY",
    publishedAt: "8th April 2026",
    readTime: "7 mins read",
    slug: "afcfta-continental-free-trade",
  },
  {
    image: "/images/insights/article-3.jpg",
    category: "Tech & Innovations",
    title: "Cybersecurity Maturity Across African Financial Markets",
    excerpt: "A comparative review of cybersecurity frameworks across Nigeria, Kenya, and South Africa and what they mean for cross-border financial services.",
    author: "CHINWE OHANELE",
    publishedAt: "2nd April 2026",
    readTime: "5 mins read",
    slug: "cybersecurity-african-financial-markets",
  },
  {
    image: "/images/insights/article-4.jpg",
    category: "Policy Analysis",
    title: "Regulatory Sandboxes and Fintech Innovation in Nigeria",
    excerpt: "How Nigeria's CBN sandbox framework has shaped the trajectory of fintech innovation and what lessons other markets can draw from the experience.",
    author: "EBERE OJADUA",
    publishedAt: "25th March 2026",
    readTime: "6 mins read",
    slug: "regulatory-sandboxes-nigeria-fintech",
  },
  {
    image: "/images/insights/article-1.jpg",
    category: "Tech & Innovation",
    title: "Biometric Identity Systems and the Privacy Paradox",
    excerpt: "As African governments scale national identity programmes, the tension between security objectives and privacy rights is becoming increasingly difficult to navigate.",
    author: "CHINWE OHANELE",
    publishedAt: "18th March 2026",
    readTime: "5 mins read",
    slug: "biometric-identity-privacy-paradox",
  },
  {
    image: "/images/insights/article-2.jpg",
    category: "Policy Analysis",
    title: "Electoral Reform and Democratic Consolidation in West Africa",
    excerpt: "A review of electoral reform efforts across ECOWAS member states and their implications for long-term democratic stability.",
    author: "DEJI MACAULAY",
    publishedAt: "10th March 2026",
    readTime: "8 mins read",
    slug: "electoral-reform-west-africa",
  },
  {
    image: "/images/insights/article-3.jpg",
    category: "Tech & Innovations",
    title: "The Role of AI in Public Sector Service Delivery",
    excerpt: "Exploring how African governments are deploying artificial intelligence to improve efficiency in healthcare, education, and revenue administration.",
    author: "EBERE OJADUA",
    publishedAt: "3rd March 2026",
    readTime: "6 mins read",
    slug: "ai-public-sector-service-delivery",
  },
  {
    image: "/images/insights/article-4.jpg",
    category: "Policy Analysis",
    title: "Energy Transition Policy and the African Development Agenda",
    excerpt: "Balancing climate commitments with development imperatives — how African governments are navigating the transition to clean energy.",
    author: "DEJI MACAULAY",
    publishedAt: "24th February 2026",
    readTime: "7 mins read",
    slug: "energy-transition-african-development",
  },
];
